// SPDX-License-Identifier: MPL-2.0

use crate::{
    device::drm::ioctl::{DrmIoctlFlags, drm_ioc, types::*},
    util::ioctl::{InData, InOutData, NoData},
};

drm_ioc!(
    DrmIoctlVersion,
    DRM_IOCTL_VERSION,
    0x00,
    InOutData<DrmVersion>,
    DrmIoctlFlags::RENDER_ALLOW
);
drm_ioc!(
    DrmIoctlGetCap,
    DRM_IOCTL_GET_CAP,
    0x0c,
    InOutData<DrmGetCap>,
    DrmIoctlFlags::RENDER_ALLOW
);
drm_ioc!(
    DrmIoctlSetClientCap,
    DRM_IOCTL_SET_CLIENT_CAP,
    0x0d,
    InData<DrmSetClientCap>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlSetMaster,
    DRM_IOCTL_SET_MASTER,
    0x1e,
    NoData,
    DrmIoctlFlags::DEFAULT
);
drm_ioc!(
    DrmIoctlDropMaster,
    DRM_IOCTL_DROP_MASTER,
    0x1f,
    NoData,
    DrmIoctlFlags::DEFAULT
);
drm_ioc!(
    DrmIoctlWaitVblank,
    DRM_IOCTL_WAIT_VBLANK,
    0x3a,
    InOutData<DrmWaitVblank>,
    DrmIoctlFlags::DEFAULT
);
drm_ioc!(
    DrmIoctlModeGetResources,
    DRM_IOCTL_MODE_GETRESOURCES,
    0xa0,
    InOutData<DrmModeGetResources>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetCrtc,
    DRM_IOCTL_MODE_GETCRTC,
    0xa1,
    InOutData<DrmModeCrtc>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeSetCrtc,
    DRM_IOCTL_MODE_SETCRTC,
    0xa2,
    InOutData<DrmModeCrtc>,
    DrmIoctlFlags::MODESET.union(DrmIoctlFlags::MASTER)
);
drm_ioc!(
    DrmIoctlModeGetEncoder,
    DRM_IOCTL_MODE_GETENCODER,
    0xa6,
    InOutData<DrmModeGetEncoder>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetConnector,
    DRM_IOCTL_MODE_GETCONNECTOR,
    0xa7,
    InOutData<DrmModeGetConnector>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetProperty,
    DRM_IOCTL_MODE_GETPROPERTY,
    0xaa,
    InOutData<DrmModeGetProperty>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetPropBlob,
    DRM_IOCTL_MODE_GETPROPBLOB,
    0xac,
    InOutData<DrmModeGetBlob>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeAddFB,
    DRM_IOCTL_MODE_ADDFB,
    0xae,
    InOutData<DrmModeFbCmd>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeRmFB,
    DRM_IOCTL_MODE_RMFB,
    0xaf,
    InOutData<u32>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeCreateDumb,
    DRM_IOCTL_MODE_CREATE_DUMB,
    0xb2,
    InOutData<DrmModeCreateDumb>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeMapDumb,
    DRM_IOCTL_MODE_MAP_DUMB,
    0xb3,
    InOutData<DrmModeMapDumb>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeDestroyDumb,
    DRM_IOCTL_MODE_DESTROY_DUMB,
    0xb4,
    InOutData<DrmModeDestroyDumb>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetPlaneResources,
    DRM_IOCTL_MODE_GETPLANERESOURCES,
    0xb5,
    InOutData<DrmModeGetPlaneRes>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeGetPlane,
    DRM_IOCTL_MODE_GETPLANE,
    0xb6,
    InOutData<DrmModeGetPlane>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeAddFB2,
    DRM_IOCTL_MODE_ADDFB2,
    0xb8,
    InOutData<DrmModeFbCmd2>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeObjectGetProps,
    DRM_IOCTL_MODE_OBJ_GETPROPERTIES,
    0xb9,
    InOutData<DrmModeObjectGetProps>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeCreatePropBlob,
    DRM_IOCTL_MODE_CREATEPROPBLOB,
    0xbd,
    InOutData<DrmModeCreateBlob>,
    DrmIoctlFlags::MODESET
);
drm_ioc!(
    DrmIoctlModeDestroyPropBlob,
    DRM_IOCTL_MODE_DESTROYPROPBLOB,
    0xbe,
    InOutData<DrmModeDestroyBlob>,
    DrmIoctlFlags::MODESET
);
